### ISSUE TITLE
Improve Colour Rendering inside of error text

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-multi-institution#140]
As a user, I'd like to be able to scan error messages quickly and take action on the error so that I can return to my original task.

I believe the WP standard is to have black text with red links for error messages:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4cdb3e3dc2f22d8d8f40c00be4f765ec5dcb40a/Screenshot%202024-03-28%20at%208.24.06%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 8.24.06 AM.png" />

Currently some error messages (consortial interface) are rendering in all red text:
<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHp4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ae79d3b07942c15de41c28144312c7490c87d59/image.png" alt="image.png" />

Mixing red and black type to provide better overall hierarchy allows the user to focus on the specific errors and action items without being overwhelmed:
<img width="1276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDN4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6456fd176607d6883c942e832ad219ccdbb7bd52/Screenshot%202024-03-19%20at%208.50.22%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 8.50.22 AM.png" />

**Comment by richard015ar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Q4-2024-65061c7b8bd3139dea5e5373/issues/pressbooks/pressbooks-multi-institution/140?planning-poker) with Zenhub @fdalcin @tw77 @ho-man-chan @SteelWagstaff @cmurtagh

**Comment by ho-man-chan** [comment]
Update:
1. Set html strong tags in error notices to be red (--pb-error-color). /spent 3h

Blocker: 
<del>1. Test is failing because the testing [pipeline](https://github.com/pressbooks/pressbooks-multi-institution/actions/runs/8548911984/job/23423500339) cannot download mariadb. 
Visting this [link](https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/ubuntu/pool/main/m/mariadb-10.5/mysql-common_10.5.24+maria~ubu2004_all.deb) at this time gives the following error:</del>
<img width="427" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGN6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc3e1c25706839c753f96c684a2fe81c542b309a/image.png" alt="image.png" />
(RESOLVED ITSELF AFTER THE NEXT DAY)


Questions: 
1. Are there any other error cases for which we want to change the styles?

**Comment by tw77** [comment]
I see the improvements on ecotest and they're appearing as expected.
