### ISSUE TITLE
Root site user with 'Administrator' user role shouldn't be able to access the institutional manager dashboard page

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-multi-institution#84]
This is very much an edge case, but replicable on dev.

If there are networks with users that were previously added to the root site (e.g. before the current Administer Network dashboard was implemented) and those users have the role of Administrator on the root site, they are currently able to view the `wp/wp-admin/index.php?page=pb_institutional_manager` page even if they aren't an institutional manager.

**Steps to replicate:**

1. On dev, add a user to the root site user list with the role of Administrator.
2. Log in as that user. You will see an additional 'Home' item in the left sidebar menu at `wp/wp-admin/index.php?page=pb_home_page` -- click the first 'Home' item that appears here.

**Expected behaviour:** There is no additional 'Home' item and clicking 'Home' returns you to the same page.

**Actual behaviour:** Clicking the first 'Home' item leads you to the institutional manager dashboard with no associated institution, books, or users.

<img width="534" alt="Screenshot 2024-03-07 at 9 45 46 AM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/887687d2-18ae-4717-9dd8-0df5c72afa9f">

**Comment by SteelWagstaff** [comment]
Agree that this should not happen. 
I've also noticed that if a super admin or network manager attempts to load `wp-admin/index.php?page=pb_institutional_manager` -- they are able to load the page, but the information about books/users will be empty because they're not an institutional manager and don't have an institution (note the warning on my local instance):
![Screenshot from 2024-03-07 10-09-41](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/3ee4b185-34cc-4f5e-b56b-0173af98d5d7)


Here's what should happen:
1. if a user is a super admin or a network manager, they should see the `network/admin.php?page=pb_network_page` page upon login. 
![screencapture-integrations-pressbooks-network-wp-wp-admin-network-index-php-2024-03-07-09_56_19](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/8c2feb3d-5b7e-4bcf-948c-898d099ddc4d)
If they directly input the `wp-admin/index.php?page=pb_home_page` URL, they should see the standard user welcome to network page:
![Screenshot from 2024-03-07 09-57-08](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/a5e64328-ca22-49bf-a2e8-c8a1bcadbe11)
if they try to visit the wp-admin/index.php?page=pb_institutional_manager page directly, they should be redirected to their network dashboard page at `network/admin.php?page=pb_network_page` instead
2. If a user is an institutional manager, they should see the new insitutional manager dashboard page `/wp-admin/index.php?page=pb_institutional_manager` upon login. If they directly input the `wp-admin/index.php?page=pb_home_page` URL, they should see the standard user welcome to network page:
![Screenshot from 2024-03-07 09-57-08](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/a5e64328-ca22-49bf-a2e8-c8a1bcadbe11)
3. If a user is not a super admin, network manager, or institutional manager, they are a 'regular user' of the network. No matter what their role is in the root site (whether administrator or subscriber or no role), they should see the standard user welcome to network page: `wp-admin/admin.php?page=pb_home_page`. The left nav menu should include Dashboard Item with a single home link that points to the standard user welcome page.
![Screenshot from 2024-03-07 10-01-05](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/9c1823f9-c2b7-438b-9713-5f9bbbd635e9). If they attempt to visit the `wp-admin/index.php?page=pb_institutional_manager` directly they should be refused access and should see a 'you don't have permission to view this' page instead.

**Comment by richard015ar** [comment]
@arzola I left a comment in the associated PR. Does it make sense to you? Maybe I am testing the wrong cases. I followed these steps: https://github.com/pressbooks/pressbooks-multi-institution/pull/85#discussion_r1519890787

**Comment by richard015ar** [comment]
It seems to be a cache problem on my local. I merged it.

**Comment by tw77** [comment]
All fixes are working. Scenarios 1, 2, and 3 are working as expected on dev.pressbooks.network.
