### ISSUE TITLE
Navigating to a root site-related admin page causes the Institutions menu item to be hidden

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-multi-institution#96]
Following this sequence leads **Institutions** to be hidden from the left sidebar menu of the network admin interface while this plugin is active. The menu item remains hidden even when navigating to the network user list or book list at the end of these steps.

1. Log in as a super admin or network manager.
2. Navigate to **Administer Network**.
3. Make sure that you are at `/wp/wp-admin/network/index.php?page=pb_network_page` and that you see **Institutions** in the left sidebar menu. 
4. Navigate to the network user list. You are now at `/wp/wp-admin/network/admin.php?page=pb_network_analytics_userlist`. Note that you still see **Institutions** in the left sidebar menu. 
5. Navigate to a root site-related admin page like **Pages** or **Stats > Analytics**. If you are a super admin, you can also navigate to **Root Site Users** at this step.
6. Note that **Institutions** has now disappeared from the left sidebar menu.
7. From here, if you navigate to the network user list again or to the book list, you will still not see **Institutions** in the left sidebar menu.

For example, if you navigate back to the network user list, you are now at `/wp/wp-admin/admin.php?page=pb_network_analytics_userlist`, the same network user list as before, but now with no `/network/` in the URL. 

Without `/network/` in the URL, **Institutions** is not displayed in the left sidebar menu.

At this point, navigating to the network dashboard, network settings or network stats pages is necessary to restore `/network/` to the URL, leading **Institutions** to appear again.

**Comment by richard015ar** [comment]
I created a PR to fix this: https://github.com/pressbooks/pressbooks-multi-institution/pull/98
The fix is available for testing on ricardodev network

**Comment by tw77** [comment]
Fixed and working as expected on dev.pressbooks.network

**Comment by SteelWagstaff** [comment]
I noticed a new regression, sadly. Not sure when/how introduced, but when I enter the root site context, the pages menu item has moved from its expected location/order:
(on dev network) -- jumped to bottom instead of being displayed between appearance & plugins
![Screenshot from 2024-03-14 10-46-42](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/5f9b19ec-6722-48d3-bfa0-06d670b06262)
(on integrations) -- stays in between appearance and plugins
![Screenshot from 2024-03-14 10-46-29](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/34c6e2f3-a9b4-4128-81bd-98544b6879c1)

To reproduce: visit https://dev.pressbooks.network/wp/wp-admin/edit.php?post_type=page and click the pages link from the admin dashboard. Notice that the location of the pages menu item moves to the bottom of the list. This shouldn't happen.

Perform the same actions at https://integrations.pressbooks.network/wp/wp-admin/edit.php?post_type=page to see expected behaviour.

See https://us02web.zoom.us/rec/share/Ci9NJWHwtMeWfP75D49m9gId1PDbsW1-I-T9LYuuDdk4UgdMn_K1be3H0WgJESYt.GhOUM_Y4SvJ7xVRN for a brief demonstration.

**Comment by tw77** [comment]
Good catch. I think this would have been introduced here. A network with an earlier iteration of this plugin (without the Institutions menu item in place from a root site-related admin page) has the Pages menu item in the correct place:
<img width="155" alt="Screenshot 2024-03-14 at 10 55 09 AM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/36b9c970-d8c0-498c-ac34-4fcd70d43c93">

**Comment by SteelWagstaff** [comment]
Yeah, I think it came from when Oscar reordered the menu to move the new 'Institutions' option higher in the display order
